### ISSUE TITLE
Fix "make test"

### ISSUE THREAD

**Issue by olabini** [otrv4/libgoldilocks#6]
rc/GENERATED/include/decaf/point_448.hxx: In constructor ‘decaf::Ed448Goldilocks::Point::Point(const decaf::FixedBlock<56>&, bool)’:
../src/GENERATED/include/decaf/point_448.hxx:321:64: error: ?: using integer constants in boolean context [-Werror=int-in-bool-context]
         if (GOLDILOCKS_SUCCESS != decode(buffer,allow_identity ? GOLDILOCKS_TRUE : GOLDILOCKS_FALSE)) {
                                                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by olabini** [comment]
OK @claucece - it's done. Can you let Mike know?

**Comment by claucece** [comment]
@olabini yes! thanks!
